export const listaCriminales = [
    {
        id_criminal: "51", 
        numero_expediente: "AS-CRM-54/26",
        alias: "La Reina Homicida",
        nombre: "Evangelina Tejera Bosada",
        estado: "Viva (Recluida y posteriormente liberada)",
        nivel_amenaza: "CRÍTICO",
        tipo_asesino: "Asesina familiar / Homicidio impulsivo por crisis de consumo",
        foto_url: "../img/sujeto68.jpg",
        victimas: 2,
        perfil: "Reina de belleza caída en desgracia, adicta crónica y narcisista fracturada.",
        perfil_psicosocial: `Un caso que conmocionó a la sociedad jarocha. Evangelina era una figura pública que, al perder su estatus y fama, se hundió en una espiral de depresión severa y consumo de cocaína y alcohol. Veía a sus hijos no como individuos, sino como cargas que le impedían recuperar su vida pasada. El crimen fue resultado de una psicosis inducida por sustancias y una profunda desconexión afectiva.`,
        resena_delictiva: `Coronada Reina del Carnaval de Veracruz en 1983. Seis años después, en 1989, asesinó a sus dos hijos (de 3 y 2 años de edad) en su departamento. Ocultó el crimen durante un mes, hasta que los olores putrefactos alertaron a su hermano. Fue sentenciada a 20 años de prisión, los cuales cumplió íntegramente.`,
        dinamica_delictiva: `Modus Operandi: Ataque intrafamiliar durante un periodo de intoxicación. Dinámica: Ante el llanto incesante de sus hijos y en medio de una crisis de abstinencia/intoxicación, los asesinó a golpes y por asfixia. Para encubrir el crimen, descuartizó los pequeños cuerpos, los incineró parcialmente en el horno de su estufa y enterró los restos en dos macetas en el balcón de su departamento.`,
        motivacion: `Desesperación inducida por drogas, rechazo materno profundo y la necesidad patológica de eliminar lo que consideraba el "obstáculo" de su vida.`
    },
    {
        id_criminal: "52", 
        numero_expediente: "AS-CRM-55/26",
        alias: "El Matahijos de La Raza",
        nombre: "Domingo Villa Zavala",
        estado: "Fallecido",
        nivel_amenaza: "CRÍTICO",
        tipo_asesino: "Homicida en masa intrafamiliar / Venganza y celopatía",
        foto_url: "../img/sujeto69.jpg",
        victimas: 6,
        perfil: "Militar frustrado, padre tiránico y celópata delirante.",
        perfil_psicosocial: `Hombre de mentalidad rígidamente machista que consideraba a su familia como propiedad exclusiva. Sufría de un cuadro severo de celos patológicos hacia su esposa. Carecía de herramientas emocionales para lidiar con el abandono matrimonial. El infanticidio múltiple no fue un accidente, sino un acto deliberado de destrucción total: aniquilar todo su linaje para castigar psicológicamente a la mujer que lo dejó.`,
        resena_delictiva: `Ocurrió en mayo de 1943 en el entonces Distrito Federal. Tras una pelea donde su esposa amenazó con abandonarlo, Domingo aprovechó que se quedó solo con sus seis hijos en un parque cerca del Hospital La Raza y los asesinó a todos uno por uno. Fue internado en el Palacio Negro de Lecumberri.`,
        dinamica_delictiva: `Modus Operandi: Sometimiento a menores de edad por figura de autoridad. Dinámica: Llevó a sus seis hijos (todos menores de 12 años) a caminar. Los reunió en una zona apartada y utilizó un puñal de carnicero para apuñalarlos directa y certeramente en el corazón, asegurándose de que ninguno sobreviviera. Luego se entregó a las autoridades.`,
        motivacion: `Venganza pasional hacia su esposa, buscando infligirle el máximo dolor posible destruyendo a su descendencia.`
    },
    {
        id_criminal: "53", 
        numero_expediente: "AS-CRM-56/26",
        alias: "El Tirador del Metro Balderas",
        nombre: "Luis Felipe Hernández Castillo",
        estado: "Vivo (Recluido psiquiátrico)",
        nivel_amenaza: "ALTO",
        tipo_asesino: "Asesino en masa (Mass shooter) / Psicótico con delirio mesiánico",
        foto_url: "../img/sujeto70.jpg",
        victimas: 2, // 2 muertos, 5 heridos.
        perfil: "Campesino con esquizofrenia no tratada, delirios de persecución y fanatismo climático.",
        perfil_psicosocial: `No es un delincuente de carrera ni un sicario, sino el producto de un quiebre mental absoluto. Padecía esquizofrenia paranoide y desarrolló un delirio mesiánico donde creía tener la "verdad" sobre el calentamiento global y la corrupción gubernamental. Carecía de filtro de la realidad; para él, cualquier figura de autoridad o persona que lo contradijera era parte de una conspiración global que debía ser eliminada.`,
        resena_delictiva: `En septiembre de 2009, desató el pánico dentro de la estación Balderas del Metro de la CDMX. Tras ser confrontado por pintar consignas en la pared del andén, sacó un revólver calibre .38 y asesinó a un policía y a un civil que intentó desarmarlo, atrincherándose en un vagón e hiriendo a 5 personas más antes de ser sometido.`,
        dinamica_delictiva: `Modus Operandi: Estallido violento en un espacio confinado de altísima densidad. Dinámica: Actuó de manera frontal, sin intentar ocultarse. Disparó a quemarropa contra quienes lo confrontaron y usó el vagón del tren como búnker, gritando consignas sin sentido sobre el fin del mundo y la política mientras recargaba su arma.`,
        motivacion: `Delirio psicótico persecutorio y la convicción distorsionada de que estaba llevando a cabo una "misión" de advertencia a la sociedad.`
    },
    {
        id_criminal: "54", 
        numero_expediente: "AS-CRM-57/26",
        alias: "La Viuda de Ciudad Juárez",
        nombre: "Ignacia Jasso",
        estado: "Fallecida",
        nivel_amenaza: "CRÍTICO",
        tipo_asesino: "Autora intelectual corporativa / Pionera del crimen organizado",
        foto_url: "../img/sujeto71.jpg",
        victimas: 15, // Número estimado de ejecuciones ordenadas.
        perfil: "Líder matriarcal del narcotráfico, pragmática, implacable y con gran visión de negocios.",
        perfil_psicosocial: `Considerada la primera gran jefa del narcotráfico en México. Ignacia era una mujer que desafió y dominó un mundo de hombres en la década de los 30. No mataba por placer o impulso, sino con una frialdad puramente empresarial. El asesinato era para ella una simple herramienta para eliminar competencia, castigar la traición o establecer control territorial fronterizo.`,
        resena_delictiva: `Operó en Ciudad Juárez en la década de 1930, controlando el tráfico de morfina, marihuana y alcohol hacia Estados Unidos durante y después de la época de la Prohibición. Ordenó ejecuciones sistemáticas de contrabandistas rivales (principalmente inmigrantes asiáticos que controlaban el opio) y consolidó el primer cártel de drogas transnacional de la frontera norte.`,
        dinamica_delictiva: `Modus Operandi: Homicidio por encargo y control paramilitar. Dinámica: Ella rara vez manchaba sus manos de sangre. Utilizaba a una red de matones y policías corruptos para emboscar a sus enemigos en el desierto o en callejones de Juárez, ejecutándolos con armas de fuego y desapareciendo los cuerpos para mantener el monopolio de las rutas.`,
        motivacion: `Lucro corporativo masivo y el establecimiento de un monopolio criminal fronterizo absoluto.`
    },
    {
        id_criminal: "55", 
        numero_expediente: "AS-CRM-58/26",
        alias: "La Homicida del Ajusco",
        nombre: "Elvira Luz Cruz",
        estado: "Viva (Liberada tras revisión de caso)",
        nivel_amenaza: "MEDIO",
        tipo_asesino: "Homicida intrafamiliar reactiva / Colapso por violencia sistémica",
        foto_url: "../img/sujeto72.jpg",
        victimas: 4,
        perfil: "Mujer rural en pobreza extrema, víctima de abuso crónico y aislamiento absoluto.",
        perfil_psicosocial: `Un caso que cambió la jurisprudencia y visibilizó la violencia de género en México. Elvira no presentaba rasgos psicopáticos ni malicia previa. Vivía en condiciones de miseria insostenible, esclavitud doméstica y violencia física y sexual dantesca por parte de su marido. Su acto fue resultado de un colapso psicológico total (Síndrome de la Mujer Maltratada) ante la incapacidad de alimentar a sus hijos y el terror al castigo de su esposo.`,
        resena_delictiva: `En 1982, en las faldas del Ajusco, CDMX. En un estado de desesperación total por falta de alimento y ante la inminente llegada de su esposo violento, asesinó a sus cuatro hijos pequeños. Fue sentenciada inicialmente, pero su caso atrajo la atención de grupos feministas. Se demostró que actuó bajo una alteración mental extrema provocada por años de abuso, logrando su liberación años después.`,
        dinamica_delictiva: `Modus Operandi: Infanticidio por piedad distorsionada y desesperación. Dinámica: Utilizando un cordón, asfixió uno por uno a sus cuatro hijos menores en su choza. Posteriormente intentó quitarse la vida, pero no lo logró, quedándose en estado de shock catatónico hasta que llegaron las autoridades.`,
        motivacion: `Desesperación absoluta, pobreza extrema y un quiebre emocional donde vio la muerte como la única salida para que sus hijos dejaran de sufrir hambre y maltrato.`
    },
    {
        id_criminal: "56", 
        numero_expediente: "AS-CRM-59/26",
        alias: "La Asesina de la Condesa",
        nombre: "Sofía Bassi",
        estado: "Fallecida",
        nivel_amenaza: "MEDIO",
        tipo_asesino: "Homicida reactiva o Encubridora corporativa",
        foto_url: "../img/sujeto74.jpg",
        victimas: 1,
        perfil: "Pintora de la alta sociedad, manipuladora, estoica y protectora familiar.",
        perfil_psicosocial: `Más allá de ser una psicópata, Sofía representa la soberbia y el código de silencio de la élite mexicana. Inteligente, articulada y teatral. Se autoinculpó del asesinato de su yerno para encubrir presumiblemente a su propia hija (un secreto a voces histórico). Su frialdad durante el proceso judicial demostró un control emocional férreo y una moralidad donde la reputación de su linaje estaba por encima de la justicia institucional.`,
        resena_delictiva: `En 1968, en una lujosísima mansión en Acapulco, Guerrero. El yerno de Sofía, el Conde italiano Cesare D'Acquarone, fue acribillado a balazos junto a la alberca. Sofía Bassi tomó la responsabilidad inmediata del crimen argumentando que fue un "accidente" mientras le mostraba un arma. Cumplió 4 años en prisión en Acapulco (donde se le permitió seguir pintando y viviendo con lujos) antes de ser liberada.`,
        dinamica_delictiva: `Modus Operandi: Ataque directo con arma de fuego (presumiblemente para proteger un secreto familiar). Dinámica: Se detonaron cinco balazos sobre el Conde. La limpieza y el montaje posterior de la escena del crimen por parte de la familia entorpecieron las pruebas, logrando que el caso se mantuviera en la opacidad jurídica y se vendiera mediáticamente como una imprudencia trágica.`,
        motivacion: `Encubrimiento familiar severo, orgullo dinástico y la eliminación de un miembro problemático que amenazaba el estatus y bienestar de su hija.`
    },
    {
    id_criminal: "57", 
    numero_expediente: "AS-CRM-60/26",
    alias: "El Descuartizador de Chihuahua",
    nombre: "Andrés Ulises Castillo Villarreal",
    estado: "Vivo (Recluido)",
    nivel_amenaza: "CRÍTICO",
    tipo_asesino: "Asesino en serie organizado / Sádico utilitario",
    foto_url: "../img/sujeto75.jpg",
    victimas: 3, // Víctimas comprobadas, sospechoso de al menos 12.
    perfil: "Sociópata metódico, sádico con fijación en el desmembramiento extremo.",
    perfil_psicosocial: `Individuo con una profunda desconexión empática y marcados rasgos de psicopatía sádica. Su agresividad estaba focalizada en hombres en situación de vulnerabilidad o adicción. El acto de quitar la vida no era su único fin; su satisfacción máxima radicaba en el proceso meticuloso de mutilar y desmembrar los cuerpos post mortem, usándolos para crear un espectáculo macabro en la vía pública y generar terror en la población.`,
    resena_delictiva: `Capturado a finales de 2015 en la ciudad de Chihuahua. Sembró pánico en la capital del estado al abandonar de forma escalonada restos humanos descuartizados en distintas colonias, a menudo exhibiendo las extremidades. Aunque las autoridades lograron comprobarle jurídicamente tres homicidios con el mismo patrón, los peritajes psicológicos y sus propias declaraciones apuntaban a una cifra negra mucho mayor. Fue sentenciado a 120 años de prisión.`,
    dinamica_delictiva: `Modus Operandi: Atraía a hombres (generalmente conocidos suyos, compañeros de trabajo o personas con adicciones) a su domicilio con la promesa de consumir drogas y convivir. Dinámica: Una vez que la víctima estaba intoxicada o distraída, la asesinaba aplastándole el cráneo con un tubo de metal pesado. Posteriormente, utilizaba una segueta para desmembrar quirúrgicamente los cuerpos, guardaba partes en su patio temporalmente y luego distribuía los restos encostalados por la ciudad, llegando a usar carretillas o juguetes (como triciclos) para transportar y exhibir los torsos.`,
    motivacion: `Sadismo puro, ejercicio de poder absoluto sobre personas en estado de indefensión y una perversa necesidad narcisista de provocar pánico, desafiando a las autoridades locales mediante la exhibición grotesca de los restos.`
    }
];